### ISSUE TITLE
NameError: name 'Network' is not defined

### ISSUE THREAD

**Issue by certik** [rwl/pylon#1]
$ pylon
Traceback (most recent call last):
  File "/home/ondrej/usr/bin/pylon", line 8, in <module>
    load_entry_point('Pylon==0.2.2', 'console_scripts', 'pylon')()
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 277, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 2180, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 1913, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/home/ondrej/usr/lib/python/Pylon-0.2.2-py2.6.egg/pylon/main.py", line 34, in <module>
    from pylon.readwrite.api \
  File "/home/ondrej/usr/lib/python/Pylon-0.2.2-py2.6.egg/pylon/readwrite/api.py", line 34, in <module>
    from pickle_reader import PickleReader
  File "/home/ondrej/usr/lib/python/Pylon-0.2.2-py2.6.egg/pylon/readwrite/pickle_reader.py", line 38, in <module>
    class PickleReader(object):
  File "/home/ondrej/usr/lib/python/Pylon-0.2.2-py2.6.egg/pylon/readwrite/pickle_reader.py", line 45, in PickleReader
    network = Network
NameError: name 'Network' is not defined

**Comment by algomaschine** [comment]
from pyvis.network import Network # this helps it
net = Network()
