### ISSUE TITLE
pylon case

### ISSUE THREAD

**Issue by luistrebejo** [rwl/pylon#3]
> > > import sys
> > > import logging
> > > import pylon
> > > logging.basicConfig(stream=sys.stdout, level=logging.debug)
> > > case=pylon.Case.load_Matpower("c:\data\case30pwl.m")

Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    case=pylon.Case.load_Matpower("c:\data\case30pwl.m")
AttributeError: type object 'Case' has no attribute 'load_Matpower'

**Comment by danielfms** [comment]
$pylon --help

Traceback (most recent call last):
  File "/usr/bin/pylon", line 9, in <module>
    load_entry_point('Pylon==0.4.4', 'console_scripts', 'pylon')()
  File "/usr/lib/python3.5/site-packages/setuptools-21.1.0-py3.5.egg/pkg_resources/**init**.py", line 542, in load_entry_point
  File "/usr/lib/python3.5/site-packages/setuptools-21.1.0-py3.5.egg/pkg_resources/**init**.py", line 2569, in load_entry_point
  File "/usr/lib/python3.5/site-packages/setuptools-21.1.0-py3.5.egg/pkg_resources/**init**.py", line 2229, in load
  File "/usr/lib/python3.5/site-packages/setuptools-21.1.0-py3.5.egg/pkg_resources/**init**.py", line 2235, in resolve
  File "/usr/lib/python3.5/site-packages/Pylon-0.4.4-py3.5.egg/pylon/**init**.py", line 17, in <module>
ImportError: No module named 'case'
